/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as QueuesRouteImport } from './routes/queues'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as MenuRouteRouteImport } from './routes/$menu/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuIndexRouteImport } from './routes/$menu/index'
import { Route as MenuMenuRouteImport } from './routes/$menu/menu'
import { Route as MenuFeedbackRouteImport } from './routes/$menu/feedback'
import { Route as MenuItemRouteImport } from './routes/$menu/$item'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiSplatRouteImport } from './routes/api/ai/$'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRoute = QueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRouteRoute = MenuRouteRouteImport.update({
  id: '/$menu',
  path: '/$menu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRouteRoute,
} as any)
const MenuMenuRoute = MenuMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MenuRouteRoute,
} as any)
const MenuFeedbackRoute = MenuFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => MenuRouteRoute,
} as any)
const MenuItemRoute = MenuItemRouteImport.update({
  id: '/$item',
  path: '/$item',
  getParentRoute: () => MenuRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSplatRoute = ApiAiSplatRouteImport.update({
  id: '/api/ai/$',
  path: '/api/ai/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$menu': typeof MenuRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/queues': typeof QueuesRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/$menu/$item': typeof MenuItemRoute
  '/$menu/feedback': typeof MenuFeedbackRoute
  '/$menu/menu': typeof MenuMenuRoute
  '/$menu/': typeof MenuIndexRoute
  '/api/ai/$': typeof ApiAiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/queues': typeof QueuesRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/$menu/$item': typeof MenuItemRoute
  '/$menu/feedback': typeof MenuFeedbackRoute
  '/$menu/menu': typeof MenuMenuRoute
  '/$menu': typeof MenuIndexRoute
  '/api/ai/$': typeof ApiAiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$menu': typeof MenuRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/queues': typeof QueuesRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/$menu/$item': typeof MenuItemRoute
  '/$menu/feedback': typeof MenuFeedbackRoute
  '/$menu/menu': typeof MenuMenuRoute
  '/$menu/': typeof MenuIndexRoute
  '/api/ai/$': typeof ApiAiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$menu'
    | '/ai'
    | '/analytics'
    | '/backup'
    | '/dashboard'
    | '/files'
    | '/login'
    | '/queues'
    | '/success'
    | '/todos'
    | '/$menu/$item'
    | '/$menu/feedback'
    | '/$menu/menu'
    | '/$menu/'
    | '/api/ai/$'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/analytics'
    | '/backup'
    | '/dashboard'
    | '/files'
    | '/login'
    | '/queues'
    | '/success'
    | '/todos'
    | '/$menu/$item'
    | '/$menu/feedback'
    | '/$menu/menu'
    | '/$menu'
    | '/api/ai/$'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$menu'
    | '/ai'
    | '/analytics'
    | '/backup'
    | '/dashboard'
    | '/files'
    | '/login'
    | '/queues'
    | '/success'
    | '/todos'
    | '/$menu/$item'
    | '/$menu/feedback'
    | '/$menu/menu'
    | '/$menu/'
    | '/api/ai/$'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuRouteRoute: typeof MenuRouteRouteWithChildren
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BackupRoute: typeof BackupRoute
  DashboardRoute: typeof DashboardRoute
  FilesRoute: typeof FilesRoute
  LoginRoute: typeof LoginRoute
  QueuesRoute: typeof QueuesRoute
  SuccessRoute: typeof SuccessRoute
  TodosRoute: typeof TodosRoute
  ApiAiSplatRoute: typeof ApiAiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues': {
      id: '/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof QueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$menu': {
      id: '/$menu'
      path: '/$menu'
      fullPath: '/$menu'
      preLoaderRoute: typeof MenuRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$menu/': {
      id: '/$menu/'
      path: '/'
      fullPath: '/$menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/$menu/menu': {
      id: '/$menu/menu'
      path: '/menu'
      fullPath: '/$menu/menu'
      preLoaderRoute: typeof MenuMenuRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/$menu/feedback': {
      id: '/$menu/feedback'
      path: '/feedback'
      fullPath: '/$menu/feedback'
      preLoaderRoute: typeof MenuFeedbackRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/$menu/$item': {
      id: '/$menu/$item'
      path: '/$item'
      fullPath: '/$menu/$item'
      preLoaderRoute: typeof MenuItemRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/$': {
      id: '/api/ai/$'
      path: '/api/ai/$'
      fullPath: '/api/ai/$'
      preLoaderRoute: typeof ApiAiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MenuRouteRouteChildren {
  MenuItemRoute: typeof MenuItemRoute
  MenuFeedbackRoute: typeof MenuFeedbackRoute
  MenuMenuRoute: typeof MenuMenuRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

const MenuRouteRouteChildren: MenuRouteRouteChildren = {
  MenuItemRoute: MenuItemRoute,
  MenuFeedbackRoute: MenuFeedbackRoute,
  MenuMenuRoute: MenuMenuRoute,
  MenuIndexRoute: MenuIndexRoute,
}

const MenuRouteRouteWithChildren = MenuRouteRoute._addFileChildren(
  MenuRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRouteRoute: MenuRouteRouteWithChildren,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  BackupRoute: BackupRoute,
  DashboardRoute: DashboardRoute,
  FilesRoute: FilesRoute,
  LoginRoute: LoginRoute,
  QueuesRoute: QueuesRoute,
  SuccessRoute: SuccessRoute,
  TodosRoute: TodosRoute,
  ApiAiSplatRoute: ApiAiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
